"""
Django settings for mainweb project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
load_dotenv(BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-CHANGE_THIS_IN_PRODUCTION')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# Erlaubte Hosts - '*' erlaubt alles auf Railway
ALLOWED_HOSTS = ['*']

# CSRF-Sicherheit für Railway & PayPal
CSRF_TRUSTED_ORIGINS = [
    'https://*.up.railway.app',
    'https://luviq-luisa-production.up.railway.app',
    'http://localhost',
    'http://127.0.0.1'
]

# CSRF Einstellungen für Proxy-Umgebungen
CSRF_USE_SESSIONS = False

# Dynamische SITE_URL für korrekte Weiterleitungen
SITE_URL = os.getenv('SITE_URL')
if not SITE_URL:
    SITE_URL = "https://webseite2-production.up.railway.app"

# SSL/HTTPS Einstellungen für Railway Proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = os.getenv('DEBUG', 'True') == 'False' # Nur in Production umleiten
SESSION_COOKIE_SECURE = os.getenv('DEBUG', 'True') == 'False'
CSRF_COOKIE_SECURE = os.getenv('DEBUG', 'True') == 'False'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',
    'axes', # Brute-Force Schutz
    'shop1', # Add your app here
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Statische Dateien in Production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware', # Brute-Force Schutz
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'shop1.middleware.PageVisitMiddleware', # Statistik-Tracking
]

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Axes Konfiguration
AXES_FAILURE_LIMIT = 5  # Versuche vor Sperrung
AXES_COOLOFF_TIME = 1   # Sperrung für 1 Stunde
AXES_LOCKOUT_TEMPLATE = 'shop1/lockout.html'
AXES_RESET_ON_SUCCESS = True


ROOT_URLCONF = 'mainweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Global templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop1.context_processors.shop_owner_check',
            ],
        },
    },
]

WSGI_APPLICATION = 'mainweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'de-de'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = []

# Whitenoise für statische Dateien in Produktion
# Cloudinary nutzen wir NUR für MEDIA (hochgeladene Produktbilder)
WHITENOISE_USE_FINDERS = True

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Rückwärtskompatibilität für django-cloudinary-storage (prüft noch das alte Attribut)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

if os.getenv('CLOUDINARY_URL'):
    STORAGES["default"] = {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    }

# Media files (User-uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

#nichts

# ═══ EMAIL-KONFIGURATION ═══

# Steuerung über .env, ob Emails via Konsole (Testing) oder SMTP (Echt) versendet werden
USE_SMTP_EMAIL = os.getenv('USE_SMTP_EMAIL', 'False') == 'True'

# E-Mail Konfiguration (SMTP)
USE_SMTP_EMAIL = os.getenv('USE_SMTP_EMAIL', 'False') == 'True'

if USE_SMTP_EMAIL or not DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp-relay.brevo.com')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
    EMAIL_TIMEOUT = 30 # Höheres Zeitlimit für Cloud-Server

    # TLS/SSL Logik: 465 nutzt SSL, 587 nutzt TLS
    if EMAIL_PORT == 465:
        EMAIL_USE_TLS = False
        EMAIL_USE_SSL = True
    else:
        EMAIL_USE_TLS = True
        EMAIL_USE_SSL = False
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@luviq-shop.de')
SITE_URL = os.getenv('SITE_URL', 'http://127.0.0.1:8000')


# ═══ SICHERHEITSEINSTELLUNGEN ═══

# Session-Sicherheit
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# Cookie-Sicherheit
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = False  # False = JS kann CSRF-Token lesen (nötig für HTMX/AJAX)
CSRF_COOKIE_SAMESITE = 'Lax'

# Clickjacking-Schutz
X_FRAME_OPTIONS = 'DENY'

# Schrägstrich-Handling
APPEND_SLASH = True

# HTTPS Umleitung in Production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# ═══ PAYPAL-KONFIGURATION ═══

PAYPAL_CLIENT_ID = os.getenv('PAYPAL_CLIENT_ID', 'sb')


# ═══ LOGIN/LOGOUT URLS ═══

# Login erfolgreich: redirect zu Home
LOGIN_REDIRECT_URL = '/'

# Nach Logout: zurück zur Login-Seite
LOGOUT_REDIRECT_URL = '/login/'

# Login-Seite URL
LOGIN_URL = '/login/'

# Standard-Primärschlüssel-Typ
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
