"""
Django settings for mainweb project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
load_dotenv(BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-CHANGE_THIS_IN_PRODUCTION')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# Erlaubte Hosts - für Production anpassen!
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'axes', # Brute-Force Schutz
    'shop1', # Add your app here
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware', # Brute-Force Schutz
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Axes Konfiguration
AXES_FAILURE_LIMIT = 5  # Versuche vor Sperrung
AXES_COOLOFF_TIME = 1   # Sperrung für 1 Stunde
AXES_LOCKOUT_TEMPLATE = 'shop1/lockout.html'
AXES_RESET_ON_SUCCESS = True


ROOT_URLCONF = 'mainweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Global templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mainweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'de-de'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (User-uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ═══ EMAIL-KONFIGURATION ═══

# Steuerung über .env, ob Emails via Konsole (Testing) oder SMTP (Echt) versendet werden
USE_SMTP_EMAIL = os.getenv('USE_SMTP_EMAIL', 'False') == 'True'

if USE_SMTP_EMAIL or not DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@meinshop.de')
SITE_URL = os.getenv('SITE_URL', 'http://127.0.0.1:8000')


# ═══ SICHERHEITSEINSTELLUNGEN ═══

# Session-Sicherheit
SESSION_COOKIE_SECURE = not DEBUG  # HTTPS only in Production
SESSION_COOKIE_HTTPONLY = True     # JS kann nicht auf Session zugreifen
SESSION_COOKIE_SAMESITE = 'Strict' # CSRF-Schutz

# Cookie-Sicherheit
CSRF_COOKIE_SECURE = not DEBUG     # HTTPS only in Production
CSRF_COOKIE_HTTPONLY = True        # JS kann nicht auf CSRF-Token zugreifen
CSRF_COOKIE_SAMESITE = 'Strict'

# Clickjacking-Schutz
X_FRAME_OPTIONS = 'DENY'

# Content Security Policy (optional, für erweiterten Schutz)
SECURE_CONTENT_SECURITY_POLICY = {
    "default-src": ("'self'",),
    "script-src": ("'self'", "cdn.jsdelivr.net"),
    "style-src": ("'self'", "cdn.jsdelivr.net", "'unsafe-inline'"),
    "font-src": ("'self'", "cdn.jsdelivr.net"),
}

# HTTPS in Production erzwingen
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# ═══ LOGIN/LOGOUT URLS ═══

# Login erfolgreich: redirect zu Home
LOGIN_REDIRECT_URL = '/'

# Nach Logout: zurück zur Login-Seite
LOGOUT_REDIRECT_URL = '/login/'

# Login-Seite URL
LOGIN_URL = '/login/'

# Standard-Primärschlüssel-Typ
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
