# Generated by Django 6.0.1 on 2026-04-23 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('stadt', models.CharField(blank=True, max_length=100, null=True)),
                ('postleitzahl', models.CharField(blank=True, max_length=10, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('land', models.CharField(blank=True, default='Deutschland', max_length=100, null=True)),
                ('geburtsdatum', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
