# Generated by Django 6.0.4 on 2026-04-23 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0002_userprofile_email_verified_verification_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('beschreibung', models.TextField(blank=True)),
                ('preis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bild', models.CharField(blank=True, default='', max_length=255)),
                ('aktiv', models.BooleanField(default=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Produkte',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Warenkorb',
                'verbose_name_plural': 'Warenkörbe',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produkt_name', models.CharField(max_length=200)),
                ('produkt_preis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produkt_bild', models.CharField(blank=True, default='', max_length=255)),
                ('menge', models.PositiveIntegerField(default=1)),
                ('hinzugefuegt_am', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop1.cart')),
            ],
            options={
                'verbose_name': 'Warenkorb-Artikel',
                'verbose_name_plural': 'Warenkorb-Artikel',
            },
        ),
    ]
