# Generated by Django 6.0.4 on 2026-04-24 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0003_produkt_cart_cartitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produkt',
            options={'ordering': ['-erstellt_am'], 'verbose_name_plural': 'Produkte'},
        ),
        migrations.AddField(
            model_name='produkt',
            name='aktualisiert_am',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='produkt',
            name='ersteller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produkte', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='bild',
            field=models.ImageField(blank=True, null=True, upload_to='produkte/'),
        ),
    ]
