# Generated by Django 6.0.4 on 2026-04-25 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0004_alter_produkt_options_produkt_aktualisiert_am_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('paid', 'Bezahlt'), ('failed', 'Fehlgeschlagen'), ('cancelled', 'Abgebrochen')], default='pending', max_length=20)),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(max_length=255)),
                ('stadt', models.CharField(max_length=100)),
                ('postleitzahl', models.CharField(max_length=10)),
                ('land', models.CharField(max_length=100)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('gesamt_betrag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bestellung',
                'verbose_name_plural': 'Bestellungen',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produkt_name', models.CharField(max_length=200)),
                ('produkt_preis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menge', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop1.order')),
            ],
            options={
                'verbose_name': 'Bestellungs-Artikel',
                'verbose_name_plural': 'Bestellungs-Artikel',
            },
        ),
    ]
