# Generated by Django 6.0.1 on 2026-05-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0005_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_payment_intent_id',
            new_name='paypal_order_id',
        ),
    ]
