# Generated by Django 6.0.1 on 2026-05-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0006_rename_stripe_payment_intent_id_order_paypal_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Datum')),
                ('visits', models.PositiveIntegerField(default=0, verbose_name='Besuche')),
            ],
            options={
                'verbose_name': 'Seitenbesuch',
                'verbose_name_plural': 'Seitenbesuche',
                'ordering': ['-date'],
            },
        ),
    ]
