# Generated by Django 6.0.1 on 2026-05-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0007_pagevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='lagerbestand',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
