# Generated by Django 6.0.1 on 2026-05-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0009_subscriber_userprofile_has_welcome_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='newsletter_gesendet',
            field=models.BooleanField(default=False),
        ),
    ]
