# Generated by Django 6.0.1 on 2026-05-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0010_produkt_newsletter_gesendet'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('bank_transfer', 'Überweisung'), ('pickup', 'Abholung (Lokal)')], default='paypal', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ausstehend / Unbezahlt'), ('paid', 'Bezahlt (Gesehen)'), ('processing', 'In Bearbeitung'), ('ready_for_shipping', 'Zum Versand bereit'), ('shipped', 'Versendet'), ('failed', 'Zahlung Fehlgeschlagen'), ('cancelled', 'Abgebrochen / Storniert')], default='pending', max_length=20),
        ),
    ]
