# Generated by Django 6.0.8 on 2026-09-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0018_visitorlog_tabelle_auch_ohne_postgres'),
    ]

    operations = [
        migrations.CreateModel(
            name='KontaktAnfrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('betreff', models.CharField(max_length=150, verbose_name='Betreff')),
                ('nachricht', models.TextField(verbose_name='Nachricht')),
                ('mail_gestartet', models.BooleanField(default=False, verbose_name='Mailversand angestoßen')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Eingegangen am')),
            ],
            options={
                'verbose_name': 'Kontaktanfrage',
                'verbose_name_plural': 'Kontaktanfragen',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
