# Generated by Django 6.0.4 on 2026-09-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0019_kontaktanfrage'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='bestaetigt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='bestaetigt_am',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
