# Generated by Django 6.0.8 on 2026-09-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0020_newsletter_double_optin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagesBesucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(db_index=True)),
                ('kennung', models.CharField(max_length=16)),
                ('pfad', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tagesbesucher',
                'verbose_name_plural': 'Tagesbesucher',
                'constraints': [models.UniqueConstraint(fields=('datum', 'kennung', 'pfad'), name='tagesbesucher_einmal_je_pfad')],
            },
        ),
    ]
