# Generated by Django 6.0.8 on 2026-09-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0022_produktnamen_ohne_verkaufsvermerk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivanfrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('richtung', models.CharField(max_length=20, verbose_name='Richtung')),
                ('teil', models.CharField(max_length=20, verbose_name='Teil')),
                ('platzierung', models.CharField(max_length=20, verbose_name='Platzierung')),
                ('bedeutung', models.TextField(blank=True, verbose_name='Was es bedeuten soll')),
                ('instagram', models.CharField(blank=True, max_length=31, verbose_name='Instagram')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('status', models.CharField(choices=[('neu', 'neu'), ('in_arbeit', 'in Arbeit'), ('erledigt', 'erledigt')], default='neu', max_length=12, verbose_name='Status')),
                ('mail_gestartet', models.BooleanField(default=False, verbose_name='Mailversand angestoßen')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Eingegangen am')),
            ],
            options={
                'verbose_name': 'Motivanfrage',
                'verbose_name_plural': 'Motivanfragen',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.AddField(
            model_name='produkt',
            name='masse',
            field=models.CharField(blank=True, help_text='z. B. „Größe M, Brustweite 56 cm". Leer = nicht angezeigt.', max_length=120, verbose_name='Maße'),
        ),
        migrations.AddField(
            model_name='produkt',
            name='material',
            field=models.CharField(blank=True, help_text='z. B. „Sweat, Baumwolle". Leer = nicht angezeigt.', max_length=80),
        ),
        migrations.AddField(
            model_name='produkt',
            name='nummer',
            field=models.PositiveIntegerField(blank=True, help_text='Laufende Nummer im Archiv (Nº 001, 002 …). Leer = nächste freie Nummer.', null=True, unique=True, verbose_name='Nummer'),
        ),
        migrations.AddField(
            model_name='produkt',
            name='technik',
            field=models.CharField(blank=True, help_text='z. B. „Bleiche" oder „Textilfarbe". Leer = nicht angezeigt.', max_length=80),
        ),
    ]
