# Generated by Django 6.0.8 on 2026-10-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0026_archivstuecke_und_stueckkennung_nachtragen'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='bild_breite',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='produkt',
            name='bild_hoehe',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
